Analys och utredning
chas-academy/u02-redesign-team3 pull request #8
Opened 2021-11-04 12:19 UTC by amawre

2021-11-05 00:12 UTC, sandra-wallen requested changes
Let's discuss my comment at friday meeting :)

2021-11-05 00:12 UTC, sandra-wallen commented on html/analys_och_utredning.html
> +
Could this be marked up further?

2021-11-06 13:04 UTC, RicardoCastelbon commented on html/analys_och_utredning.html
> +            Under senare år har Konstnärsnämnden roll som samverkanspart i olika regeringsuppdrag och som remissinstans förstärkts. Utgångspunkten för detta arbete är att se frågorna ur konstnärernas
That should be in its own p?

2021-11-06 13:06 UTC, RicardoCastelbon commented on html/analys_och_utredning.html
> +            Under senare år har Konstnärsnämnden roll som samverkanspart i olika regeringsuppdrag och som remissinstans förstärkts. Utgångspunkten för detta arbete är att se frågorna ur konstnärernas
This should be in its own p? It's a new paragraph isn't it?

2021-11-06 13:06 UTC, RicardoCastelbon commented on html/analys_och_utredning.html
> +            Avdelningen ansvarar för sammanställningar av Konstnärsnämndens styrdokument, årsredovisning, budgetunderlag, remisser och yttranden, gör uppföljningar och utvärderingar samt skapar rutin
This should be in its own p? It's a new paragraph isn't it?

2021-11-06 13:07 UTC, RicardoCastelbon commented on html/analys_och_utredning.html
> +            Avdelningen ansvarar för sammanställningar av Konstnärsnämndens styrdokument, årsredovisning, budgetunderlag, remisser och yttranden, gör uppföljningar och utvärderingar samt skapar rutin
Same with the rest

2021-11-08 20:02 UTC, amawre reviewed
Looks great!

2021-11-08 20:02 UTC, merged